### PR TITLE
Faizan interface

### PR DESCRIPTION
**Pull request by faizanali7**
hey review the code please, so I can push to main
things Changed 
- The one with JSON file is setting up JavaFX and directories; each person has to direct to their own.
- added an image of degree works 
- the one with the fxml files are auto change after using Scene builder 
-  the one with the interface main java file, I have added the functionality of the quit button
thanks, do let me know if there are other changes required.

### CODE REVIEW

**Comment by MMazenA** [comment]
I dont think we should use the Degree Works logo cause we aren't affiliated with them. Also dont commit .vscode, it should be in the .gitignore cuz its a personal file for your specific computer

**Comment by faizanali7** [comment]
No problem I can remove that png file and also put my personal stuff in gitignore

**Comment by faizanali7** [comment]
I ma trying to figure out how to put in gitignore

**Review by MMazenA — APPROVED** [review]
looks good to me, you can merge it and ill handle the .gitignore and .vscode

**Comment by faizanali7** [comment]
thanks, I was also thinking to add a link in the GUI, of the login page to go directly to the registration of wayne state as well, what do you think about that?

**Pull request merged**
